### ISSUE TITLE
Make container class more bulletproof

### ISSUE THREAD

**Issue by mhearne-usgs** [usgs/earthquake-impact-utils#64]
setString(name,string) method in container class to check to see if string of name already exists in the container and raise an Exception if it does.  Similar behavior should be implemented for all of the setter methods.

**Comment by hschovanec-usgs** [comment]
Not necessary, because the container class will be deprecated.

**Comment by hschovanec-usgs** [comment]
Not necessary, because the container class will be deprecated.
